# Generated by Django 5.2.12 on 2026-04-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank_account_number',
        ),
        migrations.AddField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('current', 'جاري'), ('savings', 'توفير'), ('investment', 'استثماري')], default='current', max_length=20, verbose_name='نوع الحساب'),
        ),
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الرصيد'),
        ),
        migrations.AddField(
            model_name='bank',
            name='currency',
            field=models.CharField(choices=[('SAR', 'ريال سعودي'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو')], default='SAR', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='bank',
            name='iban',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم IBAN'),
        ),
        migrations.AddField(
            model_name='bank',
            name='swift_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='رمز SWIFT'),
        ),
    ]
