version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8096:8096"
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_ENV=production
    volumes:
      - media_data:/app/media
    restart: always

volumes:
  media_data:
