# Generated by Django 5.2.12 on 2026-04-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('core', '0002_permission_role_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False, help_text='الأدوار الأساسية لا يمكن حذفها', verbose_name='دور نظام'),
        ),
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('manager', 'مدير'), ('auditor', 'مدقق'), ('branch_employee', 'موظف فرع')], default='branch_employee', max_length=20, verbose_name='نوع الدور'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='الفرع الذي ينتمي إليه الموظف (مطلوب لموظفي الفروع)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='branches.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='المستخدمين المحميين لا يمكن حذفهم أو تعديلهم', verbose_name='محمي'),
        ),
    ]
