# Generated by Django 5.2.12 on 2026-06-13 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('title', models.CharField(max_length=300, verbose_name='اسم المساحة')),
                ('tenant_name', models.CharField(max_length=300, verbose_name='المستأجر')),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المساحة (م²)')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإيجار الشهري')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='space_rentals', to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'إيجار مساحة',
                'verbose_name_plural': 'إيجارات المساحات',
                'ordering': ['-created_at'],
            },
        ),
    ]
