# Generated by Django 6.0.4 on 2026-04-10 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        ('branches', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ الإجمالي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الحالي')),
                ('analytical_account', models.CharField(blank=True, max_length=50, verbose_name='الحساب التحليلي')),
                ('supplier_account', models.CharField(default='21101001', max_length=50, verbose_name='حساب المورد')),
                ('cost_center', models.CharField(blank=True, max_length=50, verbose_name='مركز التكلفة')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب البنكي')),
                ('bank_code', models.CharField(blank=True, max_length=50, verbose_name='رمز البنك')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('proposed', 'مقترح'), ('first_approved', 'موافقة مبدئية'), ('audited', 'تمت المراجعة'), ('final_approved', 'اعتماد نهائي'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('proposed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاقتراح')),
                ('first_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة المبدئية')),
                ('audited_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التدقيق')),
                ('final_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد النهائي')),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_payments', to=settings.AUTH_USER_MODEL, verbose_name='المدقق')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='banks.bank', verbose_name='البنك')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('final_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_payments', to=settings.AUTH_USER_MODEL, verbose_name='الموافق النهائي')),
                ('first_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approved_payments', to=settings.AUTH_USER_MODEL, verbose_name='موافق مبدئي')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_payments', to=settings.AUTH_USER_MODEL, verbose_name='اقترحه')),
            ],
            options={
                'verbose_name': 'طلب دفع',
                'verbose_name_plural': 'طلبات الدفع',
                'ordering': ['-created_at'],
                'permissions': [('can_propose', 'يمكنه اقتراح الدفعة'), ('can_first_approve', 'يمكنه الموافقة المبدئية'), ('can_audit', 'يمكنه التدقيق المالي'), ('can_final_approve', 'يمكنه الاعتماد النهائي'), ('can_reject', 'يمكنه الرفض')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500, verbose_name='الإجراء')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='الحالة الجديدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.paymentrequest', verbose_name='طلب الدفع')),
            ],
            options={
                'verbose_name': 'سجل مراجعة',
                'verbose_name_plural': 'سجل المراجعة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=50, verbose_name='كود المورد')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الحالي')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الدفعة المقترحة')),
                ('proposed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مقترح المشتريات')),
                ('abu_alaa_proposed', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='اقتراح أبو علاء')),
                ('sultan_approval', models.CharField(choices=[('pending', 'جاري المعالجة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='موافقة سلطان')),
                ('auditor_status', models.CharField(choices=[('pending', 'جاري المعالجة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة المدقق')),
                ('abu_alaa_final', models.CharField(choices=[('pending', 'جاري المعالجة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='اعتماد أبو علاء النهائي')),
                ('cfo_approval', models.CharField(choices=[('pending', 'جاري المعالجة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='موافقة المدير المالي')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الفاتورة')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الفاتورة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.paymentrequest', verbose_name='طلب الدفع')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_items', to='suppliers.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'بند الدفع',
                'verbose_name_plural': 'بنود الدفع',
                'ordering': ['created_at'],
            },
        ),
    ]
