# Generated by Django 5.2.12 on 2026-06-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='باركود الصنف')),
                ('name', models.CharField(max_length=300, verbose_name='اسم الصنف')),
                ('package', models.CharField(help_text='مثل: علبة، كرتون، 500 مل', max_length=100, verbose_name='العبوة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='suppliers.supplier', verbose_name='الشركة / المورد')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الأصناف',
                'ordering': ['name'],
            },
        ),
    ]
